version: '3.4'

services:
  backend:
    build: 
      context: backend
      args:
        - MODE=production
    ports:
      - 8082:8082
    environment:
      - MODE=production
  frontend:
    build: frontend
    ports:
      - 8080:8080
    depends_on:
      - backend
